	const formularioInspeccion = {
    	
    	tipo_accion: null,
		region: null,
		modulopredio_municipio: null,
		modulopredio_localidad: null,
		anio: null,
		nombre_predio: null,
		modulopredio_cup: null,
		folio: null,
		razon_social: null,
		paraje: null,
		coordenadas_utm_x: null,
		coordenadas_utm_y: null,
		metros_sobre_nivel_mar: null,
		fecha_inicio: null,
		fecha_termino: null,
		zona_critica: null,
		total_participantes: null,
		vehiculos_sin_irregularidades: null,
		vehiculos_revisados: null,
		total_personas: null,
		num_orden: null,
		tipo_documento: null,
		num_documento: null,
		dependencia_expide_documento: null,
		agencia_ministerio_solicita_dictamen: null,
		medidas_seguridad: null,
		valor_comercial: null,
		impacto_ambiental: null,
		reparacion_danio: null,
		total_dictamen: null,
		estatus_industria: null,
		codigo_identificacion: null,
		registro_forestal_nacional: null,
		observaciones: null
	}
		
	export default formularioInspeccion